pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {
        stage('Pre-Build Info') {
            steps {
                echo "Build number is: ${env.BUILD_NUMBER}"
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/praveenkuluru/anshulc55_Jenkins_Upgradev3.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying to Tomcat...'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
